# Generated by Django 5.0.2 on 2024-03-04 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='name',
            new_name='quantity',
        ),
    ]
