# Generated by Django 5.0.2 on 2024-03-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_recipe_author_recipe_created_on_recipe_update_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
